P1Z7/frontend

- app/(route)/setting/profile/page.tsx
- app/_components/input/InputFile.tsx
- app/_components/input/InputText.tsx
> ⚡️ hotfix: InputFile

- app/_components/input/InputFile.tsx
- app/_components/input/InputText.tsx
> ⚡️ hotfix (Input) : children을 optional prop으로

- app/(route)/post/_components/DetailInfo.tsx
- app/(route)/post/_components/FunnelTitle.tsx
- app/(route)/post/_components/MainInfo.tsx
- app/(route)/post/_components/PostFooter.tsx
- app/(route)/post/_components/StarInfo.tsx
- app/(route)/post/_components/SubInfo.tsx
- app/(route)/post/page.tsx
- app/(route)/signup/_components/GenericForm.tsx
- app/_components/Dropdown.tsx
- app/_components/ProgressBar.tsx
- app/_components/bottom-sheet/StarBottomSheet.tsx
- app/_components/card/ArtistProfile.tsx
- app/_components/input/InputFile.tsx
- app/_components/input/InputText.tsx
- app/_components/input/SearchInput.tsx
- app/_components/modal/AddressModal.tsx
- app/_components/modal/CalendarModal.tsx
- app/_components/modal/ModalFrame.tsx
- app/_hooks/useFunnel.tsx
- app/_types/index.ts
- tailwind.config.ts
- formProvider & 공용 input 컴포넌트를 사용하는 방식으로 변경했습니다.
- **((((놀라지ㅏ마시라 ㅋ)))) css 대충 추가함~** tailwind 이제는 익숙해졋다 우하하
- 글자수 제한 기능 추가했습니다.
- InputFile에서 변경한 게 있어서 해당 부분 코멘트 남겨 놓을게요!
- 연예인 부분 바텀시트 띄워놓는 것까지만 일단 해놨어요! (그룹 선택하면 해당 그룹 멤버 데이터 api 호출하는 느낌이라 지금 로직 추가할 수 있는게 있나 싶어서....... 일단 보류)
- 이제 /post 대충 마무리된 것 같아서 수정 페이지로 넘어갈게용
- 다들 홧팅 ❤️‍🔥❤️‍🔥❤️‍🔥❤️‍🔥❤️‍🔥
> ♻️ refactor: post 페이지 input 리팩토링

- app/(route)/setting/favorite/page.tsx
- app/(route)/signup/_components/ArtistCard.tsx
- app/(route)/signup/_components/ProfileSetup.tsx
- app/(route)/signup/_components/SearchArtist.tsx
- app/(route)/signup/_components/SignupFunnelTitle.tsx
- app/(route)/signup/_components/step/AccountInfo.tsx
- app/(route)/signup/_components/step/MyArtistsInfo.tsx
- app/(route)/signup/_components/step/ProfileInfo.tsx
- app/(route)/signup/page.tsx
- 검색 기능은 백에서 db 구조 전달주시면 맞춰서 다시 수정해야 할 수도 있을 것 같아용
> ✨ feat: /signup 검색 기능 추가

- app/(route)/event/[id]/post/page.tsx
- app/_components/Review.tsx
- 에러 메시지를 상수로 분리했습니다.
- 테일윈드 스타일을 수정했습니다.
> 🩹 chore: 후기 작성 페이지 에러 메시지 상수화

- app/_components/modal/AddressModal.tsx
- pr 전 모두 `npm run build` 사용하여 type 에러 안나는지 확인.
- pr 올린 뒤 vercel 에서 에러 체크 실패하면 해당 링크 들어가서 수정사항 확인하고 수정 후 커밋 올리기 (vercel 체크 에러난 경우 pr 머지 금지)
> 🩹 chore(AddressModal.tsx): 타입 수정

- app/globals.css
- tailwind.config.ts
> 🩹 chore: main 색상 추가

- app/_components/ProgressBar.tsx
- progressBar 색상 purple로 변경했습니다.
- 얜 진짜 색상 설정만 해준거라 바이패스해두될듯 . . . .
> 💄 design: progressBar 색상 설정 완료

- app/_components/ArtistCard.tsx
- app/_components/button/index.tsx
> 🩹 chore: ArtistCard 컴포넌트 width 수정

- app/_components/modal/CalendarModal.tsx
- app/_constants/calendarStyle.ts
- app/_constants/new.css
- app/_styles/customCalendar.css
- tsconfig.json
- 캘린더 디자인 완성했습니다.
- 기여우니까 사진 2ㄱㅐ 히히
- 와 오랜만에 css 쓰니까 진짜 멘붕,,,,, styled component 그립다......~~
> 💄 design: 캘린더 디자인 완료

- app/_components/Tabs.tsx
> 💄 design: 탭 디자인 구현

- app/_components/Header.tsx
header를 fixed에서 sticky로 변경했습니다
> 💄 design(Header.tsx): 헤더 디자인 sticky로 수정

- app/_api/api.ts
- app/_components/bottom-sheet/StarBottomSheet.tsx
- app/_types/reqType.ts
- next.config.mjs
- vercel.json
- api 함수 구현 완료했습니다.
1. new Api(토큰)으로 사용할 api 객체 생성 (변수명은 편하신대로 지어주시면 됩니다)
1-1. 토큰을 생성자에 param으로 넣어주는 이유는 class 안에서 하려고 해봤더니 authProvider로 감싸져 있지 않다고 안되더라구요ㅠㅠ,,,, (저는 임시로 후딱 짜느라고 값 바로 넣었어요 ㅎ)
2. 원하는 메소드 사용: `get`/`post`/`put`/`delete`
3. post와 put의 경우 **req type을 제네릭으로 넣어주면 body에서 편하게 자동 완성**을 사용하실 수 있습니다.
4. 제네릭 타입 별칭은 `reqType.ts` 참고 부탁드립니다! (코멘트 달아놓을게요~!)
- 사용법 더 궁금하신거 편하게 코멘트 남겨주세요!
- 일단 get, post까지는 테스트 해봤고 (당연함........ㅎㅎ put이랑 delete는 api가 없음..........ㅎㅎ)
- type에도 지금 있는 api까지만 넣어놨습니다!
> ✨ feat: 공통 api 함수 구현 완료

- .prettierrc
- app/(route)/post/_components/_inputs/SubInput.tsx
- app/_components/ArtistCard.tsx
- app/_components/BottomNav.tsx
- app/_components/ProgressBar.tsx
- app/_components/bottom-sheet/EventTypeBottomSheet.tsx
- app/_components/button/index.tsx
- app/globals.css
- tailwind.config.ts
메인 컬러 purple -> 핑크로 수정했습니다.
색 진짜 너무 이쁘다,,
> ⚡️ fix: 컬러 팔레트 수정

- app/(route)/(header)/event/[id]/edit/_components/EditContent.tsx
- app/(route)/post/_components/_inputs/MainInput.tsx
- app/_components/bottom-sheet/CalendarBottomSheet.tsx
- app/_components/modal/AddressModal.tsx
- app/_components/modal/AlertModal.tsx
- app/_components/modal/ModalMaterial.tsx
- 모든 모달에 x버튼이 들어갔었는데, 디자이너님과 상의한 결과 AlertModal에서는 제외하도록 수정하였습니다.
- ~~post UI 커밋에 수정사항이 많았는데 여기서 반영이 안돼서ㅠㅠ 여기서도 고쳐버리면 컨플릭트가 많이 날 것 같아서 걔 먼저 머지되면 얘도 머지할게요~~
- 수정 완료!
> ⚡️ fix: Alert모달에서 x버튼 삭제

- app/(route)/(header)/event/[id]/edit/_components/EditContent.tsx
- app/(route)/(header)/event/[id]/edit/page.tsx
- app/(route)/post/_components/ImageSection.tsx
- app/(route)/post/_components/_inputs/StarInput.tsx
- app/(route)/post/_components/_inputs/SubInput.tsx
- app/_components/input/InputText.tsx
> 💄 design: edit 페이지 UI 완료

- app/(route)/(bottom-nav)/search/page.tsx
- app/(route)/(header)/event/[id]/_components/tab/DescriptionTab.tsx
- app/_components/bottom-sheet/BottomSheetMaterial.tsx
- app/_components/bottom-sheet/GiftsBottomSheet.tsx
- app/_components/card/HorizontalEventCard.tsx
- public/icon/arrow-down_sm.svg
검색 페이지 UI를 완성했습니다.
https://github.com/P1Z7/frontend/assets/83965026/0cb42436-849d-4008-930d-78e482d91e18
> 💄 design: 검색 페이지 UI 완성

- app/(route)/post/_components/_inputs/MainInput.tsx
- app/_components/input/InputArea.tsx
- app/_components/input/InputText.tsx
> feat: InputText, InputArea "isEdit"에 따라 수정메시지 출력

- app/_components/chip/Chip.tsx
> ⚡️ fix: Chip css 수정

- app/(route)/(bottom-nav)/mypage/_components/MyKaKaoMap.tsx
- app/(route)/(bottom-nav)/mypage/_components/tab/MyCalendarTab.tsx
- 캘린더 전체 UI 수정은 다른 페이지 API 먼저 연결하고 다시 하겠습니다 이러다 진짜 캘린더만 잡고있을 것 같아서..
> 🐛bug : 캘린더 UI 오류 수정

- app/(route)/signup/_components/SearchArtist.tsx
- app/(route)/signup/_components/step/AccountInfo.tsx
- app/(route)/signup/_components/step/MyArtistsInfo.tsx
> ✨ feat(SearchArtist): 무한스크롤

- app/_components/GenericFormProvider.tsx
- 지금 아직 로그인 안했을 때 post & edit 페이지 접근을 안막아놔서 버튼눌러도 아무 액션이 없었어요ㅠㅠㅠ 임시로 toast랑 리다이렉트시키는 코드 가져왔습니다,,,
> 🐛 bug: 로그인 안하고 등록했을 시 아무 액션 없는 문제 수정(임시)

- app/(route)/(bottom-nav)/search/page.tsx
- app/(route)/event/[eventId]/_components/Banner.tsx
- app/(route)/event/[eventId]/_components/tab/ReviewTab.tsx
- app/(route)/event/[eventId]/page.tsx
- app/_components/Alert.tsx
- app/_components/layout/DottedLayout.tsx
- app/_components/skeleton/DeferredSuspense.tsx
- app/_components/skeleton/HorizontalEventCardSkeleton.tsx
- app/_components/skeleton/ReviewSkeleton.tsx
- app/_hooks/useInfiniteScroll.ts
- app/_types/getResType.ts
- package-lock.json
- package.json
- 검색 페이지 및 후기 페이지 스켈레톤 UI를 구현했습니다.
- 행사 상세 페이지에서 수정요청이 있을 시 alert이 뜨도록 했습니다.
https://github.com/P1Z7/frontend/assets/83965026/180b1082-0f68-4ba8-89be-b1aebedbb12d
https://github.com/P1Z7/frontend/assets/83965026/0dd1f554-2513-4c5d-9a86-eb226c5898b5
```tsx
<DeferredSuspense fallback={<HorizontalEventCardSkeleton />} isFetching={isFetching} />
```
> ✨ feat: 검색 및 후기 페이지 스켈레톤 UI 구현

- app/(route)/event/[eventId]/_components/tab/ReviewTab.tsx
- app/(route)/event/[eventId]/post/page.tsx
> ⚡️ hotfix: 후기 좋아요 및 등록 수정

- app/_components/button/HeartButton.tsx
- app/_components/card/VerticalEventCard.tsx
> ⚡️ fix: 좋아요 새로고침 시 바로 반영되도록 수정

- app/(route)/event/[eventId]/approve/[editId]/page.tsx
- app/(route)/event/[eventId]/edit/_components/EditContent.tsx
- app/(route)/event/[eventId]/edit/page.tsx
- app/(route)/post/_components/PostFrame.tsx
- app/(route)/post/_components/_inputs/SubInput.tsx
- app/_components/GenericFormProvider.tsx
> 💄 design: 라디오버튼 선택 안함 시 bg색 추가

- app/_components/Analytics.tsx
- app/layout.tsx
> 🩹 chore: GTM 스크립트 추가

- app/(route)/(bottom-nav)/mypage/_components/tab/MyArtistTab.tsx
- app/(route)/(bottom-nav)/mypage/_components/tab/MyCalendarTab/ChipButtons.tsx
- app/(route)/(bottom-nav)/mypage/_components/tab/MyCalendarTab/index.tsx
- app/(route)/event/[eventId]/_components/Banner.tsx
> 🩹 chore: 행사 상세 페이지 디자인 및 오타 수정

- app/(route)/(bottom-nav)/mypage/_components/tab/MyReviewTab/MyReview.tsx
- app/_types/index.ts
- app/_utils/signupValidation.ts
- 마이페이지 후기에서 아티스트 이름 안보이는 부분 수정
> ⚡️ hotfix: 마이페이지 후기 UI 간단한 수정

- app/(route)/(bottom-nav)/page.tsx
> 🩹 chore: 모바일 홈 헤더 높이 수정

- app/(route)/(bottom-nav)/mypage/_components/UserProfile.tsx
> 🩹 chore(UserProfile): 간단한 코드 수정

- app/(route)/post/_components/_inputs/SubInput.tsx
> ⚡️ fix: post 특전 수정

- app/_components/GenericFormProvider.tsx
- app/_constants/errorMsg.ts
- app/_types/errorMsgType.ts
- app/_utils/changeImgUrl.ts
> ⚡️ fix: 사진 용량 에러 시 토스트 추가

- app/(route)/_components/Footer.tsx
> ⚡️fix: 푸터 수정

- app/(route)/event/[eventId]/_components/tab/DescriptionTab.tsx
> 🩹 fix: 이미지 breakpoint 수정

- app/(route)/_components/Footer.tsx
- 푸터 디자인 수정사항 반영하고 링크 연결 완료했습니다
> 💄 design(Footer.tsx): 푸터 디자인 변경사항 반영

- app/(route)/(bottom-nav)/signin/page.tsx
- app/(route)/setting/password/page.tsx
- app/(route)/setting/profile/page.tsx
- app/_components/ArtistCard.tsx
- app/_components/MyArtistList.tsx
- app/_components/card/HorizontalEventCard.tsx
- app/_components/card/VerticalEventCard.tsx
자동완성 되도록 Input autoComplete 설정
아티스트 수정 페이지 placeholder 수정
비밀번호 변경 완료 알림이 없어요
행사 카드 hover 이미지 크게
아티스트 카드 hover 이미지 어둡게
> 🐛 : 240224 QA

- app/(route)/_components/SearchBar.tsx
- app/(route)/page.tsx
- app/(route)/search/_components/ArtistList.tsx
- app/(route)/search/_components/ArtistProfile.tsx
- app/(route)/search/_components/EventList.tsx
- app/(route)/search/_components/Filter.tsx
- app/(route)/search/_components/FilterButton.tsx
- app/(route)/search/_components/StatusButton.tsx
- app/(route)/search/_hooks/useFetch.ts
- app/(route)/search/_hooks/useSearch.tsx
- app/(route)/search/_hooks/useShowOnScroll.ts
- app/(route)/search/page.tsx
- app/_components/bottom-sheet/CalendarBottomSheet.tsx
- app/_components/bottom-sheet/EventBottomSheet.tsx
- app/_components/bottom-sheet/GiftsBottomSheet.tsx
- app/_components/bottom-sheet/content/CalendarContent.tsx
- app/_components/header/MobileHeader.tsx
- app/_components/header/PcHeader.tsx
- app/_types/index.ts
- app/_types/queryType.ts
- public/icon/search.svg
- 검색 페이지 로직 및 컴포넌트를 분리했습니다.
- 행사 유형 및 행사 상태 필터를 추가했습니다.
- 아티스트 검색 결과를 추가했습니다.
- 홈페이지 검색바를 구현했습니다.
https://github.com/P1Z7/frontend/assets/83965026/a3ed0716-75e2-4025-8689-6ffcb920e53e
https://github.com/P1Z7/frontend/assets/83965026/cae32019-7df5-4444-9cd6-e2dd9364374c
- 지금 검색 결과가 없을 때 위 스크린샷처럼 뜨도록 해놨는데 좀 딱딱한거 같아서 좋은 멘트 추천 부탁드립니다...!!
> ♻️ refactor & ✨ feat: 검색 페이지 리팩토링 및 추가 기능 구현

- app/_components/GenericFormProvider.tsx
- 회원가입하려다가 자동저장되는.. (^^) 에러를 발견해서 급하게 fix해서 올립니다!
> 🐛 fix: 회원가입에서도 자동저장되는 문제 수정

- app/(route)/mypage/_components/SettingList.tsx
- app/(route)/mypage/_components/UserProfile.tsx
- app/(route)/signup/page.tsx
- app/_api/api.ts
- app/_components/bottom-sheet/MyPageBottomSheet.tsx
- /mypage 로그아웃 안되는 문제
- /mypage 바텀시트, 모달 동시에 열리는 문제
- /signup UI 두번씩 나오는 문제
> 🐛Bug: 자잘한 오류 해결

- app/(route)/signup/_components/SearchArtist.tsx
- ArtistCard 컴포넌트 변경으로 onChange 이벤트가 무시되는 문제 해결
> ⚡️ fix(SearchArtist.tsx): 회원가입 아티스트 버튼 안눌리는 문제 해결

- app/(route)/mypage/_components/tab/MyReviewTab/MyReview.tsx
- app/_api/api.ts
- app/_components/bottom-sheet/ControlMyDataBottomSheet.tsx
- app/_components/card/HorizontalEventCard.tsx
- app/_components/card/KebabContents.tsx
- 탈퇴 시 json 오류 
- 후기, 게시글 삭제 지 바텀시트, 모달 이중으로 뜨는 문제
> ⚡️ fix: /mypage 모달, 탈퇴 로직 수정
